[package]
name = "sbox_rust-web-client"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = "0.11.3"
reqwest = { version = "0.12", features = ["blocking"] }
scraper = "0.19"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = "1.38.0"
